// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniStationeryManagement.Mvc.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniStationeryManagement.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614163235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniStationeryManagement.Mvc.Models.StationeryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("StationeryCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bút & Viết"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Giấy & Sổ viết"
                        });
                });

            modelBuilder.Entity("MiniStationeryManagement.Mvc.Models.StationeryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinStock")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("StationeryItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            LastUpdatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinStock = 10,
                            Name = "Bút Bi Thiên Long",
                            Price = 5000m,
                            Quantity = 50,
                            Sku = "VPP-BUT-01",
                            Supplier = "Tập đoàn Thiên Long"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            LastUpdatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinStock = 5,
                            Name = "Sổ Lò Xo A5 Hải Tiến",
                            Price = 25000m,
                            Quantity = 3,
                            Sku = "VPP-SO-02",
                            Supplier = "Công ty Giấy Hải Tiến"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            LastUpdatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinStock = 5,
                            Name = "Ram Giấy Double A A4",
                            Price = 85000m,
                            Quantity = 15,
                            Sku = "VPP-GIAY-03",
                            Supplier = "Double A Quốc Tế"
                        });
                });

            modelBuilder.Entity("MiniStationeryManagement.Mvc.Models.StationeryOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("StationeryOrder", (string)null);
                });

            modelBuilder.Entity("MiniStationeryManagement.Mvc.Models.StationeryOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("StationeryItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StationeryItemId");

                    b.ToTable("StationeryOrderItem", (string)null);
                });

            modelBuilder.Entity("MiniStationeryManagement.Mvc.Models.StationeryItem", b =>
                {
                    b.HasOne("MiniStationeryManagement.Mvc.Models.StationeryCategory", "Category")
                        .WithMany("StationeryItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniStationeryManagement.Mvc.Models.StationeryOrderItem", b =>
                {
                    b.HasOne("MiniStationeryManagement.Mvc.Models.StationeryOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniStationeryManagement.Mvc.Models.StationeryItem", "StationeryItem")
                        .WithMany()
                        .HasForeignKey("StationeryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("StationeryItem");
                });

            modelBuilder.Entity("MiniStationeryManagement.Mvc.Models.StationeryCategory", b =>
                {
                    b.Navigation("StationeryItems");
                });

            modelBuilder.Entity("MiniStationeryManagement.Mvc.Models.StationeryOrder", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
